# argparse
set(ARGPARSE_INSTALL OFF CACHE INTERNAL "" FORCE)
set(ARGPARSE_BUILD_TESTS OFF CACHE INTERNAL "" FORCE)
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/argparse")

# indicators
set(INDICATORS_BUILD_TESTS OFF CACHE INTERNAL "" FORCE)
set(INDICATORS_SAMPLES OFF CACHE INTERNAL "" FORCE)
add_subdirectory("${CMAKE_CURRENT_LIST_DIR}/indicators")
