name: Release
on:
  release:
    types: [released]

jobs:
  winget:
    runs-on: windows-latest
    steps:
      - name: Update WinGet Fork
        uses: tgymnich/fork-sync@v2
        with:
          merge_method: rebase
          token: ${{secrets.WINGET_TOKEN}}

      - name: Get Version
        id: version
        shell: pwsh
        run: |
          $VERSION=("${{github.event.release.name}}").Trim("v")
          "version=$VERSION" >> $env:GITHUB_OUTPUT

      - name: Upload to WinGet
        uses: vedantmgoyal2009/winget-releaser@v2
        with:
          identifier: craftablescience.VPKEdit
          version: ${{steps.version.outputs.version}}
          installers-regex: 'VPKEdit-Windows-Installer-msvc-Release\.zip$'
          token: ${{secrets.WINGET_TOKEN}}
